-- ================================================================
-- DDL: CRTIDX01.sql
-- INDEXES: PI (Plastic Issuance) Database
-- DESCRIPTION: Index definitions for optimal query performance
-- ================================================================

-- Card Master Indexes
CREATE UNIQUE INDEX IX_CM_CARD_NUM
    ON TB_CARD_MASTER (CARD_NUMBER ASC)
    USING STOGROUP PIST01
    PRIQTY 1000
    SECQTY 500
    BUFFERPOOL BP1;

CREATE INDEX IX_CM_ACCOUNT
    ON TB_CARD_MASTER (ACCOUNT_NUMBER ASC)
    USING STOGROUP PIST01
    PRIQTY 500
    SECQTY 200;

CREATE INDEX IX_CM_CUSTOMER
    ON TB_CARD_MASTER (CUSTOMER_ID ASC)
    USING STOGROUP PIST01
    PRIQTY 500
    SECQTY 200;

CREATE INDEX IX_CM_STATUS
    ON TB_CARD_MASTER (CARD_STATUS ASC, EXPIRY_DATE ASC)
    USING STOGROUP PIST01
    PRIQTY 200
    SECQTY 100;

CREATE INDEX IX_CM_EXPIRY
    ON TB_CARD_MASTER (EXPIRY_DATE ASC, CARD_STATUS ASC)
    USING STOGROUP PIST01
    PRIQTY 200
    SECQTY 100;

CREATE INDEX IX_CM_BRANCH
    ON TB_CARD_MASTER (BRANCH_CODE ASC)
    USING STOGROUP PIST01
    PRIQTY 100
    SECQTY 50;

-- Card Transaction Indexes
CREATE UNIQUE INDEX IX_CT_TXN_ID
    ON TB_CARD_TRANSACTION (TXN_ID ASC)
    USING STOGROUP PIST01
    PRIQTY 2000
    SECQTY 1000;

CREATE INDEX IX_CT_CARD_DATE
    ON TB_CARD_TRANSACTION (CARD_NUMBER ASC, TXN_DATE DESC)
    USING STOGROUP PIST01
    PRIQTY 2000
    SECQTY 1000;

CREATE INDEX IX_CT_SETTLE
    ON TB_CARD_TRANSACTION (SETTLE_FLAG ASC, TXN_DATE ASC)
    USING STOGROUP PIST01
    PRIQTY 500
    SECQTY 200;

-- Card Status History Indexes
CREATE INDEX IX_CSH_CARD
    ON TB_CARD_STATUS_HISTORY (CARD_NUMBER ASC, STATUS_DATE DESC)
    USING STOGROUP PIST01
    PRIQTY 500
    SECQTY 200;
