/*-----------------------------------------------------------------*/
/* SAS PROGRAM: SASRCN01                                            */
/* DESCRIPTION: SETTLEMENT RECONCILIATION ANALYTICS                 */
/* INPUT: SETTLEMENT SAS FEED FILE (CSV FROM STLMT400)              */
/* OUTPUT: RECONCILIATION ANALYSIS AND TREND REPORTS                */
/*-----------------------------------------------------------------*/

OPTIONS MPRINT SYMBOLGEN NOCENTER LS=132 PS=60;

%LET RUN_DATE = %SYSFUNC(TODAY(), DATE9.);
%LET INPUT_PATH = SETTLE.DAILY.SAS.FEED;

TITLE1 "Settlement Reconciliation Analytics";
TITLE2 "Run Date: &RUN_DATE";

/*----- STEP 1: READ SETTLEMENT FEED FILE -------------------------*/
DATA WORK.SETTLE_DATA;
    INFILE "&INPUT_PATH" DLM=',' FIRSTOBS=1;
    INPUT
        SETTLE_DATE :$10.
        NETWORK_ID  :$4.
        TXN_COUNT   :9.
        TXN_AMOUNT  :15.2
        FEE_AMOUNT  :13.2
        NET_AMOUNT  :15.2
        RECON_STATUS :$2.
    ;
    FORMAT TXN_AMOUNT FEE_AMOUNT NET_AMOUNT DOLLAR15.2;

    /* Derive additional fields */
    SETTLE_DT = INPUT(SETTLE_DATE, YYMMDD10.);
    FORMAT SETTLE_DT DATE9.;

    FEE_PCT = (FEE_AMOUNT / TXN_AMOUNT) * 100;
    FORMAT FEE_PCT 5.2;

    LENGTH NETWORK_NAME $12;
    SELECT (NETWORK_ID);
        WHEN ('VISA') NETWORK_NAME = 'VISA';
        WHEN ('MC  ') NETWORK_NAME = 'MASTERCARD';
        WHEN ('STAR') NETWORK_NAME = 'STAR';
        OTHERWISE      NETWORK_NAME = 'OTHER';
    END;

    LENGTH RECON_STATUS_DESC $15;
    SELECT (RECON_STATUS);
        WHEN ('BL') RECON_STATUS_DESC = 'BALANCED';
        WHEN ('OB') RECON_STATUS_DESC = 'OUT-OF-BALANCE';
        WHEN ('PE') RECON_STATUS_DESC = 'PENDING';
        OTHERWISE    RECON_STATUS_DESC = 'UNKNOWN';
    END;
RUN;

/*----- STEP 2: SUMMARY BY NETWORK --------------------------------*/
PROC SUMMARY DATA=WORK.SETTLE_DATA NWAY;
    CLASS NETWORK_NAME;
    VAR TXN_COUNT TXN_AMOUNT FEE_AMOUNT NET_AMOUNT;
    OUTPUT OUT=WORK.NETWORK_SUMMARY (DROP=_TYPE_ _FREQ_)
        SUM(TXN_COUNT)=TOTAL_TXN
        SUM(TXN_AMOUNT)=TOTAL_AMOUNT
        SUM(FEE_AMOUNT)=TOTAL_FEES
        SUM(NET_AMOUNT)=TOTAL_NET
        MEAN(FEE_PCT)=AVG_FEE_PCT;
RUN;

PROC PRINT DATA=WORK.NETWORK_SUMMARY NOOBS;
    TITLE3 "Settlement Summary by Network";
    FORMAT TOTAL_AMOUNT TOTAL_FEES TOTAL_NET DOLLAR15.2
           AVG_FEE_PCT 5.2;
RUN;

/*----- STEP 3: RECONCILIATION STATUS CHECK -----------------------*/
PROC FREQ DATA=WORK.SETTLE_DATA;
    TITLE3 "Reconciliation Status Distribution";
    TABLE RECON_STATUS_DESC * NETWORK_NAME / NOCUM NOPERCENT;
RUN;

/*----- STEP 4: DAILY TREND ANALYSIS ------------------------------*/
PROC SUMMARY DATA=WORK.SETTLE_DATA NWAY;
    CLASS SETTLE_DT;
    VAR TXN_COUNT TXN_AMOUNT;
    OUTPUT OUT=WORK.DAILY_TREND (DROP=_TYPE_ _FREQ_)
        SUM(TXN_COUNT)=DAILY_TXN
        SUM(TXN_AMOUNT)=DAILY_AMOUNT;
RUN;

PROC PRINT DATA=WORK.DAILY_TREND NOOBS;
    TITLE3 "Daily Settlement Trend";
    FORMAT DAILY_AMOUNT DOLLAR15.2;
RUN;

/*----- STEP 5: EXCEPTION REPORT ----------------------------------*/
DATA WORK.EXCEPTIONS;
    SET WORK.SETTLE_DATA;
    WHERE RECON_STATUS NE 'BL';
RUN;

PROC PRINT DATA=WORK.EXCEPTIONS NOOBS;
    TITLE3 "Reconciliation Exceptions - Requires Attention";
    VAR SETTLE_DATE NETWORK_NAME TXN_COUNT TXN_AMOUNT
        NET_AMOUNT RECON_STATUS_DESC;
    FORMAT TXN_AMOUNT NET_AMOUNT DOLLAR15.2;
RUN;

/*----- CLEANUP ---------------------------------------------------*/
PROC DELETE DATA=WORK.SETTLE_DATA
                  WORK.NETWORK_SUMMARY
                  WORK.DAILY_TREND
                  WORK.EXCEPTIONS;
RUN;
