-- ================================================================
-- DML: QRYCRD01.sql
-- DESCRIPTION: Common query patterns for PI system
-- ================================================================

-- Query 1: Find active cards expiring within 60 days
SELECT CARD_NUMBER, ACCOUNT_NUMBER, CUSTOMER_ID,
       FIRST_NAME, LAST_NAME, EXPIRY_DATE
FROM TB_CARD_MASTER
WHERE CARD_STATUS = 'AC'
  AND EXPIRY_DATE <= CURRENT DATE + 60 DAYS
ORDER BY EXPIRY_DATE;

-- Query 2: Card status summary by branch
SELECT BRANCH_CODE,
       CARD_STATUS,
       COUNT(*) AS CARD_COUNT,
       SUM(AVAILABLE_BALANCE) AS TOTAL_BALANCE
FROM TB_CARD_MASTER
GROUP BY BRANCH_CODE, CARD_STATUS
ORDER BY BRANCH_CODE, CARD_STATUS;

-- Query 3: Daily transaction summary
SELECT TXN_DATE,
       TXN_TYPE,
       COUNT(*) AS TXN_COUNT,
       SUM(TXN_AMOUNT) AS TOTAL_AMOUNT
FROM TB_CARD_TRANSACTION
WHERE TXN_DATE = CURRENT DATE
GROUP BY TXN_DATE, TXN_TYPE;

-- Query 4: Unsettled transactions
SELECT T.TXN_ID, T.CARD_NUMBER, T.TXN_AMOUNT,
       T.TXN_DATE, C.ACCOUNT_NUMBER
FROM TB_CARD_TRANSACTION T
JOIN TB_CARD_MASTER C ON T.CARD_NUMBER = C.CARD_NUMBER
WHERE T.SETTLE_FLAG = 'N'
  AND T.TXN_DATE < CURRENT DATE
ORDER BY T.TXN_DATE;

-- Query 5: Card status change history
SELECT H.CARD_NUMBER, H.PREVIOUS_STATUS, H.NEW_STATUS,
       H.REASON_CODE, H.STATUS_DATE, H.REQUESTOR_ID
FROM TB_CARD_STATUS_HISTORY H
WHERE H.STATUS_DATE >= CURRENT DATE - 7 DAYS
ORDER BY H.STATUS_DATE DESC, H.CARD_NUMBER;
